import { GoogleGenAI, Modality } from '@google/genai';
import { UploadedImage } from '../types';

// The API key MUST be obtained exclusively from the environment variable `process.env.API_KEY`
if (!process.env.API_KEY) {
  // In a real app, you might want to handle this more gracefully,
  // but for this context, throwing an error is fine.
  alert('API_KEY environment variable not set. Please set it in your .env.local file.');
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateThumbnail = async (
  image: UploadedImage,
  title: string,
  style: string
): Promise<string> => {
  const model = 'gemini-2.5-flash-image';

  const prompt = `
    Create a compelling YouTube thumbnail based on the provided image.
    Video Title: "${title}"
    Style: "${style}"

    Instructions:
    1. Analyze the input image and video title.
    2. Incorporate visually appealing text of the video title (or a shortened, catchy version of it) onto the image. The text should be prominent, readable, and match the requested style.
    3. Adjust colors, lighting, and composition to make the thumbnail more eye-catching and fit the "${style}" aesthetic.
    4. Do NOT change the core subject of the image. Enhance it, don't replace it.
    5. The final output must be just the edited image.
  `;

  const imagePart = {
    inlineData: {
      data: image.base64,
      mimeType: image.mimeType,
    },
  };

  const textPart = {
    text: prompt,
  };

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [imagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });
    
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:image/png;base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error('Error generating thumbnail:', error);
    throw new Error('Failed to generate thumbnail. Please check the console for more details.');
  }
};
